#!/usr/bin/env bash
# install NGINX on server
sudo apt -y update
sudo apt -y upgrade
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "HolbertonSchool" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
