#!/usr/bin/env bash
# Not Found
sudo apt -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chmod a+w /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i '/listen 80 default_server/a error_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
