#!/usr/bin/env bash
# configure HAProxy .
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0.\*
echo "frontend load-banlancer
    bind *:80
    mode http
    default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 1877-web-01 34.75.155.93:80 check
    server 1877-web-02 34.73.7.18:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
