#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
i=1
while [ $i -le 10 ]
do
if [[ $i -eq 4 ]]
then
echo $"bad luck"
((i++))
fi
if [[ $i -eq 8 ]]
then
echo $"good luck"
((i++))
fi
echo $"Holberton School"
((i++))
done