#!/bin/bash
#displays numbers from 1 to 20 and:
i=1
while [ $i -le 20 ]
do
if [[ $i -eq 5 ]]
then
echo $"bad luck from China"
fi
if [[ $i -eq 10 ]]
then
echo $"bad luck from Japan"
fi
if [[ $i -eq 18 ]]
then
echo $"bad luck from Italy"
fi
echo $i
((i++))
done