#!/usr/bin/env bash
#this will hack th s%^&*% out of people

h="holbertonschool"

if [ -e $h ]
then
        echo "$h file exists"

if [ -s $h ]
then
        echo "holbertonschool file is not empty"
else
        echo "holbertonschool file is empty"
fi

if [ -f $h ]
then
        echo "holbertonschool is a regular file"
fi
else
        echo "holbertonschool file does not exist"
fi